### ISSUE TITLE
No email when new users' account is approved by administrator

### ISSUE THREAD

**Issue by elenaustyugova** [o360/backend#19]
**1. Description**
When new user account is approved by an administrator, an email should be sent to user.

**2. Steps to reproduce**

1. Login as a new user
2. Approve new user by administrator (Go to Administration-> Users -> Find new user -> Click "Approve")

**3. Actual result**
Approved user does not receive an email with a confirmation of his account

**4. Expected result**
Approved user receives an email with a confirmation of his account

**5. Environment:** dev

**Req ID:** REQF_login-002

**Comment by maximskripnik** [comment]
Was an environment setup issue, fixed now
