### ISSUE TITLE
Add default project to the system

### ISSUE THREAD

**Issue by elenaustyugova** [o360/backend#27]
Add [default entities](https://docs.google.com/document/d/1V919xdWLo0fFEqhu-3-uXO7h2_5Qief5VpmzpktNkcg/edit) that should appear in UI once the system is deployed

- [ ] Add stage to a docker compose to apply dump to fresh postgres install, when needed
- [ ] Test the deployment

**Comment by yaroslavdudchenko** [comment]
TODO: Ask Egor why FlywayInitializer implemented via asEagerSingleton and not OnApplicationStart
